Добавил перевод из published в freelancers_detected и из него в in_work
SagirovVitaliy/web_project pull request #12
Opened 2020-10-18 23:54 UTC by SagirovVitaliy

2020-10-19 16:49 UTC, sobrabd requested changes

2020-10-19 16:49 UTC, sobrabd commented on webapp/__init__.py
> +    def personal_area_customer_in_work(task_id):
Сейчас не работает, поскольку в шаблоне передается 
personal_area_customer_in_work без аргумента task_id
и на этом стопорится нужно прокинуть этот парметр в шаблон

аналогично для второго эндпоинта

2020-10-19 17:05 UTC, sobrabd commented on webapp/__init__.py
> +        if form.validate_on_submit():
нужно не только поменять статус нужно прикрепить фрилансеров  к таске

2020-10-19 17:05 UTC, sobrabd commented on webapp/__init__.py
> +            status = Status.query.filter(Status.status == 'in_work').one()
соответственно, нужно не только поменять статус но и открепить других фрилансеров от такски

2020-10-21 19:48 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/personal_area_freelancer/<int:task_id>', methods=['GET', 'POST'])
тут на самом деле немного по-другому должно работать когда мы переходим по этому эндпоинту мы должны видеть все таски, которые привязаны к фрилансеру
и для аналогичного эндпоинта нужно чтобы были видны все таски заказчика
то есть эндпоинт не привязан к какой-то конкретной таске,он привязан к пользователю
а самого пользоватлея нужно будет брать из сессии 
https://flask-login.readthedocs.io/en/latest/#how-it-works
при этом для незарегистрированного пользователя эти эндпоинты должны быть не доступны

2020-10-21 19:48 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/personal_area_freelancer/<int:task_id>', methods=['GET', 'POST'])
возможно можно будет сделать 1 эндпоинт а рендерить 2 разных шаблона в зависимости от того какая роль у пользователя

2020-10-21 19:48 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/personal_area_freelancer/<int:task_id>', methods=['GET', 'POST'])
Предлагаю пока не отрисовывать эти шаблоны, а просто добавить формы, которые необходимы для реализации логики соответсвующей этим статусам

2020-10-21 23:48 UTC, SagirovVitaliy reviewed
Не успел проверить как работает, но придётся тестить пока без юзера.

2020-10-26 10:37 UTC, sobrabd reviewed
модели для таски выглядят норм, попробуй доделать удаление добавление фрилансерво

2020-10-26 10:37 UTC, sobrabd commented on webapp/model.py
> +        return '{} {} {} {} {} {}'.format(self.id, self.task_name, self.status, self.price, self.deadline, self.freelancer_responded)
можно сделать по аналогии с тем как Миша сдела вчера pretify

2020-10-26 10:37 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/personal_area_freelancer/<int:user_id>', methods=['GET', 'POST'])
не забыть переработать когда подъедет login чтобы брать ползователя из сессии также для 2 эндпоинта

2020-10-26 13:02 UTC, SagirovVitaliy reviewed
В общем всё исправил, но проблема  с тем что у нам может быть всего один freelancer_responded не решена. Надо либо создавать отдельную модель, либо как то это класть в m2m и брать от туда, но я не знаю как это сделать.

2020-10-26 15:47 UTC, sobrabd commented on webapp/model.py
> +    freelancer_responded = db.Column(
тут 3 поля freelancer_responded, freelancer, freelancer_tasks должно остаться 2 это исполнитель и те кто откликнулись
в принципе у тебя сейчас они оба есть исполнитель - это фрилансер
а те кто откликнулись они сейчас храняться в поле freelancer_tasks (название нужно поменять) например на freelancers_responded

2020-10-26 15:47 UTC, sobrabd commented on webapp/model.py
> +    freelancer_responded = db.Column(
соответсвенно лишнее поле нужно удалить
+ добавь поле аналогичное freelancers_tasks в user так чтобы можно было посмотреть глядяна объект юзера на какие таски он откликнулся

2020-10-27 07:54 UTC, sobrabd requested changes
Сейчас не нужно делать роуты
1) добавить поле м2м
2)  добавить форму которая позволяет добавлятьпотенциальных исполнителей + меняет статус. (пока юзер у нас в сессии не хранится можно добавлять фрилансера через форму)
3) добавить форму которая выбирает исполнителя + меняет статус + убирает потенциальных исполнителей (3 пункт опционально, можно и не убирать, на случай если будет отказ чтобы предложить этут таску тем, кто на нее уже окликался)

пусть формы будут пока доступны из какого-то тестового роута
на реализацию тех роутов которые ты хочешь сделать есть отдельные задачи

2020-10-27 07:54 UTC, sobrabd commented on webapp/model.py
> -freelancers_tasks = db.Table('freelancers_tasks',
Почему ты убрал всех фрилансеров из этой модели, должно было остаться 2 тот кто будет делать и все те кто откликнулся

2020-10-27 07:54 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/personal_area_customer_in_work_two/<int:customer_id>/<int:task_id>')
не будем использовать этот роут. см чат

2020-10-27 18:44 UTC, SagirovVitaliy reviewed
В общем в роуте (personal_area_freelancer) где мы выводим все заказы для фрилансера, есть ошибка, я вывожу все заказы со статусом published и получается, что как только один из фрилансеров нажимает "отклик" у нас статус меняется на freelancers_detected и другие фрилансеры его не видят. Пока думаю как решить эту проблему.

По поводу эндпоинтов думаю поменяем и сделаем всё красиво, когда сделаем login/logout

2020-10-27 20:47 UTC, sobrabd approved these changes
https://stackoverflow.com/questions/8603088/sqlalchemy-in-clause
Вроде норм, чтобы таска не пропадала можно фильтровать сразу по 2-м статусам когда выводим все таски для фрилансера.
Потом еще нужно будет пофиксить конфликты.

2020-10-28 14:32 UTC, agate-agate approved these changes
По-моему всё ок - даю зелёный свет на мёрдж)

2020-10-28 16:27 UTC, merged